### ISSUE TITLE
Decide on which classes do we want, and how will we use hierarchy for them.

### ISSUE THREAD

**Issue by a-amaria** [Miridinia/AEDA.mmxvi-mmxvii#1]

**Comment by Miridinia** [comment]
Tema 8 – Boleias Partilhadas (Parte 1)
Uma empresa deseja explorar o conceito de car­pooling e ride­sharing, e pretende criar um sistema para a
gestão de uma rede social de partilha de boleias. Poderá haver dois tipos de utilizadores: os registados no
sistema e aqueles que utilizam o sistema ocasionalmente. Entre os utilizadores, também haverá aqueles que
desejam disponibilizar as suas viaturas, e aqueles que não têm viaturas para partilhar, mas apenas partilham as
viagens.
Quando um utilizador disponibiliza o seu veículo no sistema, deverá indicar o número de lugares disponíveis, e o
itinerário que realiza como uma lista de pontos de passagem, sendo o primeiro ponto o endereço de origem da
viagem e o último ponto o endereço de destino. Utilizadores que possam ter interesse em partilhar a viagem toda
ou trechos das viagens, podem candidatar­se aos lugares disponíveis. É possível que fiquem vagos lugares no
decorrer da viagem, podendo estar disponíveis a quem desejar realizar o trecho ou parte do trecho
remanescente.
Sendo construído em torno do conceito de redes socais, o sistema também privilegia a formação de grupos de
partilha de viagem entre pessoas próximas entre si; os utilizadores, ao se registarem no sistema, podem
associar­se como “buddy” de outros utilizadores – desta forma é possível criar uma rede de relações diretas e
indiretas entre utilizadores. O serviço de partilha é mantido pelos próprios utilizadores. Os utilizadores que têm
pág. 5
Algoritmos e Estruturas de Dados 2016/17 Trabalho prá湢co – Parte 1
viatura própria e a partilham no sistema, pagam apenas uma taxa de manutenção; os utilizadores registados sem
viatura, pagam uma mensalidade fixa de manutenção mais o que realizarem em número de viagens, durante o
mês; os utilizadores que utilizam o serviço esporadicamente devem efetuar pagamento em cada viagem.
O sistema, para além de guardar as relações de amizade (“buddies”) dos utilizadores registados, também
mantém o histórico das viagens realizadas, incluindo o nome do utilizador proprietário da viatura, os pontos de
origem e destino da viagem, a hora de início e de fim, assim como o dia em que foi realizada. Adicionalmente
poderá considerar veículos diferentes, nomeadamente veículos ligeiros (5 lugares), vans (de 7 lugares), entre
outras opções.

**Comment by Miridinia** [comment]
Portanto: 
Utilizadores, e depois sub-classes de Condutor e Passageiro. 
Veiculo, para cada carro...
Viagem, para o historico de viagens, e uma classe data também...

**Comment by Miridinia** [comment]
Vamos fazer isso das classes hoje na aula, tipo um diagrama de classes mas sem ser tão formal :D

**Comment by Miridinia** [comment]
> User 
> Registado
>         >Condutor
>         >Passageiro
> Guest
> 
> Buddy (formar uma relação entre 2 users private: user 1 e user2)
> Data 
> Viagem 
> Veiculo
> Carro (5 lugares) (?)
> Van (7 lugares) (?) 
> Locais 

Ficheiro no qual está guardado o histórico das viagens. 
EVERYTHING IS ENGLISH.
